name: Build and Push Docker image

on:
  push:
    branches:
      - airbyte/update_source_mongodb-v2
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Build with Gradle
        run: ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:buildConnectorImage

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag airbyte/source-mongodb-v2:dev sibengineering/airbyte-source-mongodb:1.3.0.8

      - name: Push Docker image to Docker Hub
        run: docker push sibengineering/airbyte-source-mongodb:1.3.0.8